export const TYPES = {
  SET_NAVIGATION_STATE: 'SET_NAVIGATION_STATE',
  SET_CURRENT_ROUTE_NAME: 'SET_CURRENT_ROUTE_NAME',
  GET_CATEGORY_START: 'GET_CATEGORY_START',
  GET_CATEGORY_FAILED: 'GET_CATEGORY_FAILED',
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
  GET_PRODUCT_START: 'GET_PRODUCT_START',
  GET_PRODUCT_FAILED: 'GET_PRODUCT_FAILED',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
};
